---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-service-account
  namespace: customer-service-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/msk-dev-customer-service-ns-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-service-account
  namespace: order-service-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::230476794540:role/msk-dev-order-service-ns-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-service-account
  namespace: catalog-service-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::230476794540:role/msk-dev-catalog-service-ns-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-service-account
  namespace: order-history-service-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::230476794540:role/msk-dev-order-history-service-ns-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-service-account
  namespace: notification-service-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::230476794540:role/msk-dev-notification-service-ns-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-service-account
  namespace: payments-service-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::230476794540:role/msk-dev-payments-service-ns-role
